### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by vladdu** [lindenbaum/maven-erlang-plugin#3]
Hi! What is the status of this project? Is it stable and working?

**Comment by olle** [comment]
Hi @vladdu sorry for the loooong wait. Working and maintaining the plug-in was a great ride - at the time. But, in this modern day and age, you'll most likeley do better looking at the more _living_ set of dependency and build tools for Erlang.

**Comment by vladdu** [comment]
I assumed that much 😄 Thanks!
